version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: always

  db:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data/
    restart: always

  
  DB_PANELS:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - nginx
    restart: always

  backend:
    build: 
      context: server
    container_name: backend
    command: ["/app/docker/app.sh"]
    ports:
      - 8000:8000
    env_file:
      - prod.env
    depends_on:
      - db
    restart: always

  frontend:
    build: 
      context: client
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always
    x-develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

volumes:
  pgadmin: